Add the MultiResCNN Model
dalgu90/icd-coding-benchmark pull request #24
Opened 2022-03-13 13:52 UTC by SuhasShanbhogue

The code contains the files related to MultiResCNN.
Feel free to nitpick any changes :)

2022-04-23 06:36 UTC, SuhasShanbhogue commented on src/models/multirescnn.py
> +
Done

2022-04-23 06:37 UTC, SuhasShanbhogue commented on src/utils/model_utils.py
> +                   lowercase_and_digits_replaced_with_zeros_found*100.0/len(word_alphabet), not_match*100.0/len(word_alphabet)))
Fixed

2022-04-23 06:38 UTC, SuhasShanbhogue commented on src/modules/schedulers.py
> +
Changed in the new commit

2022-04-24 04:34 UTC, dalgu90 commented on src/modules/schedulers.py
> +
Oh it seems that the manual implementation came back to the branch after the recent commit (c3877518)

2022-04-24 12:34 UTC, abheesht17 requested changes
@SuhasShanbhogue, looks like you reverted some of your changes in this commit: https://github.com/dalgu90/icd-coding-benchmark/pull/24/commits/c38775180a966b81487f84d47e55e30131d4f465. Could you please look into this? And please run all pre-commit hooks on the files you've changed. Also, why do we have `laat_trainer.py` in this PR?

2022-04-24 12:34 UTC, abheesht17 commented on configs/multirescnn_default.yml
> +    use_gpu: false
Why is this set to false?

2022-04-24 12:34 UTC, abheesht17 commented on src/modules/schedulers.py
> +    return LambdaLR(optimizer, lr_lambda, last_epoch)
Why do we have this function if we have imported it from transformers? Remove this.

2022-04-24 12:34 UTC, abheesht17 commented on src/trainers/laat_trainer.py
> +import math
Why do we have `laat_trainer.py` in this PR?

2022-04-24 16:31 UTC, dalgu90 commented on configs/multirescnn_default.yml
> +            k: 8
The name and the param of the metric don't match (P@5 vs. P@8). In the CAML paper, all the model was tuned to P@8, but you can check the MultiResCNN paper for exact criteria for early stopping.

2022-04-24 16:32 UTC, dalgu90 reviewed
Here's another small thing

2022-04-24 19:13 UTC, dalgu90 commented
The results on the MIMIC-III top-50 (old) dataset. The numbers seem lower than what is in the MultiResCNN paper.
(P@5: 0.638, Micro-F1: 0.673, Macro-F1: 0.608 in the paper)
```
2022-04-24 15:07:56,531 — src.datasets.base_dataset — INFO — Loaded dataset from datasets/mimic3_50_old/test.json (1729 examples)
loading pretrained embeddings from processed_full.embed
2022-04-24 15:07:58,061 — src.trainers.base_trainer — INFO — Initializing BaseTrainer
2022-04-24 15:08:07,340 — src.trainers.base_trainer — INFO — Loaded checkpoint from best-45.pth
2022-04-24 15:08:07,767 — src.trainers.base_trainer — INFO — Use GPU
2022-04-24 15:08:07,767 — src.trainers.base_trainer — INFO — Evaluating on test dataset
2022-04-24 15:08:15,600 — src.trainers.base_trainer — INFO —    prec_at_5: 0.625795
2022-04-24 15:08:15,600 — src.trainers.base_trainer — INFO —    prec_at_8: 0.510628
2022-04-24 15:08:15,600 — src.trainers.base_trainer — INFO —     macro_f1: 0.591825
2022-04-24 15:08:15,600 — src.trainers.base_trainer — INFO —     micro_f1: 0.659234
2022-04-24 15:08:15,600 — src.trainers.base_trainer — INFO —    macro_auc: 0.896389
2022-04-24 15:08:15,601 — src.trainers.base_trainer — INFO —    micro_auc: 0.923049
2022-04-24 15:08:15,601 — src.trainers.base_trainer — INFO — Saving result on results/MultiResCNN_mimic3_50_old/test_result.json

```

2022-05-02 05:43 UTC, SuhasShanbhogue commented on src/trainers/laat_trainer.py
> +import math
Sorry will fix this.

2022-05-02 05:43 UTC, SuhasShanbhogue commented on src/modules/schedulers.py
> +    return LambdaLR(optimizer, lr_lambda, last_epoch)
Thank you for pointing out.

2022-05-16 17:41 UTC, dalgu90 reviewed
Hey @SuhasShanbhogue , I added a few comments on the code. Also, please create 4 different configs for each dataset. (MIMIC-III full/top-50 & new/old) Please note that the full and top-50 dataset uses different stopping criteria.

2022-05-16 17:41 UTC, dalgu90 commented on configs/multirescnn_default.yml
> +    filter_size: "3,5,9,15,19,25"
I know this string format of the `filter_size` argument is what was in the original code.
But we can make it a list (i.e. `[3, 5, 9, 15, 19, 25]`) and remove split() and type conversion in the code. I've done that in Fusion code ([link](https://github.com/dalgu90/icd-coding-benchmark/blob/main/configs/fusion/mimic3_50_old.yml#L42)).

2022-05-16 17:41 UTC, dalgu90 commented on configs/multirescnn_default.yml
> +        name: prec_at_8
In the original code, the MIMIC-III top-50 is trained with P@5 stopping criteria. ([link](https://github.com/foxlf823/Multi-Filter-Residual-Convolutional-Neural-Network#usage))

2022-05-16 17:41 UTC, dalgu90 commented on configs/multirescnn_default.yml
> +preprocessing:
This `preprocessing` block is unnecessary for the model training/testing. Please remove this block.

2022-05-28 14:26 UTC, dalgu90 commented
This is the results on the current code/configs:

- MIMIC-III top-50 (old) (P@5: 0.638, Micro-F1: 0.673, Macro-F1: 0.608 in the paper)
```
2022-05-27 11:34:12,805 — src.datasets.base_dataset — INFO — Loaded dataset from datasets/mimic3_50_old/test.json (1729 examples)
loading pretrained embeddings from processed_full.embed
2022-05-27 11:34:14,014 — src.trainers.base_trainer — INFO — Initializing BaseTrainer
2022-05-27 11:34:18,348 — src.trainers.base_trainer — INFO — Loaded checkpoint from best-14.pth
2022-05-27 11:34:18,355 — src.trainers.base_trainer — INFO — Use GPU
2022-05-27 11:34:18,356 — src.trainers.base_trainer — INFO — Evaluating on test dataset
2022-05-27 11:34:21,189 — src.trainers.base_trainer — INFO —    prec_at_5: 0.640023
2022-05-27 11:34:21,189 — src.trainers.base_trainer — INFO —    prec_at_8: 0.519158
2022-05-27 11:34:21,189 — src.trainers.base_trainer — INFO —     macro_f1: 0.589514
2022-05-27 11:34:21,189 — src.trainers.base_trainer — INFO —     micro_f1: 0.670533
2022-05-27 11:34:21,189 — src.trainers.base_trainer — INFO —    macro_auc: 0.899234
2022-05-27 11:34:21,189 — src.trainers.base_trainer — INFO —    micro_auc: 0.927863
2022-05-27 11:34:21,190 — src.trainers.base_trainer — INFO — Saving result on results/MultiResCNN_mimic3_50_old/test_result.json
```

- MIMIC-III top-50 (new)
```
2022-05-28 03:36:48,582 — src.datasets.base_dataset — INFO — Loaded dataset from datasets/mimic3_50/test.json (3234 examples)
2022-05-28 03:36:49,643 — src.trainers.base_trainer — INFO — Initializing BaseTrainer
2022-05-28 03:36:55,193 — src.trainers.base_trainer — INFO — Loaded checkpoint from best-7.pth
2022-05-28 03:36:55,288 — src.trainers.base_trainer — INFO — Use GPU
2022-05-28 03:36:55,288 — src.trainers.base_trainer — INFO — Evaluating on test dataset
2022-05-28 03:37:03,231 — src.trainers.base_trainer — INFO —    prec_at_5: 0.672604
2022-05-28 03:37:03,232 — src.trainers.base_trainer — INFO —    prec_at_8: 0.549204
2022-05-28 03:37:03,232 — src.trainers.base_trainer — INFO —     macro_f1: 0.644801
2022-05-28 03:37:03,232 — src.trainers.base_trainer — INFO —     micro_f1: 0.718600
2022-05-28 03:37:03,232 — src.trainers.base_trainer — INFO —    macro_auc: 0.926459
2022-05-28 03:37:03,232 — src.trainers.base_trainer — INFO —    micro_auc: 0.949508
2022-05-28 03:37:03,232 — src.trainers.base_trainer — INFO — Saving result on results/MultiResCNN_mimic3_50/test_result.json
```

- MIMIC-III full (old) (P@8: 0.734, Micro-F1: 0.552, Macro-F1: 0.552 in the paper)
```
2022-05-28 10:03:43,204 — src.datasets.base_dataset — INFO — Loaded dataset from datasets/mimic3_full_old/test.json (3372 examples)
2022-05-28 10:03:44,408 — src.trainers.base_trainer — INFO — Initializing BaseTrainer
2022-05-28 10:03:47,759 — src.trainers.base_trainer — INFO — Loaded checkpoint from best-25.pth
2022-05-28 10:03:47,774 — src.trainers.base_trainer — INFO — Use GPU
2022-05-28 10:03:47,774 — src.trainers.base_trainer — INFO — Evaluating on test dataset
2022-05-28 10:04:27,896 — src.trainers.base_trainer — INFO —    prec_at_8: 0.736099
2022-05-28 10:04:27,896 — src.trainers.base_trainer — INFO —   prec_at_15: 0.583472
2022-05-28 10:04:27,896 — src.trainers.base_trainer — INFO —     macro_f1: 0.077205
2022-05-28 10:04:27,896 — src.trainers.base_trainer — INFO —     micro_f1: 0.550036
2022-05-28 10:04:27,896 — src.trainers.base_trainer — INFO —    macro_auc: 0.907786
2022-05-28 10:04:27,897 — src.trainers.base_trainer — INFO —    micro_auc: 0.986263
2022-05-28 10:04:27,897 — src.trainers.base_trainer — INFO — Saving result on results/MultiResCNN_mimic3_full_old/test_result.json
```

- MIMIC-III full (new)
```
2022-05-28 09:41:42,509 — src.datasets.base_dataset — INFO — Loaded dataset from datasets/mimic3_full/test.json (3372 examples)
2022-05-28 09:41:43,718 — src.trainers.base_trainer — INFO — Initializing BaseTrainer
2022-05-28 09:41:47,032 — src.trainers.base_trainer — INFO — Loaded checkpoint from best-34.pth
2022-05-28 09:41:47,047 — src.trainers.base_trainer — INFO — Use GPU
2022-05-28 09:41:47,047 — src.trainers.base_trainer — INFO — Evaluating on test dataset
2022-05-28 09:42:26,531 — src.trainers.base_trainer — INFO —    prec_at_8: 0.739324
2022-05-28 09:42:26,532 — src.trainers.base_trainer — INFO —   prec_at_15: 0.587169
2022-05-28 09:42:26,532 — src.trainers.base_trainer — INFO —     macro_f1: 0.084015
2022-05-28 09:42:26,532 — src.trainers.base_trainer — INFO —     micro_f1: 0.558163
2022-05-28 09:42:26,532 — src.trainers.base_trainer — INFO —    macro_auc: 0.914338
2022-05-28 09:42:26,532 — src.trainers.base_trainer — INFO —    micro_auc: 0.986860
2022-05-28 09:42:26,532 — src.trainers.base_trainer — INFO — Saving result on results/MultiResCNN_mimic3_full/test_result.json
```

2022-06-02 01:32 UTC, abheesht17 requested changes
Thank you, @dalgu90, for figuring out how to get comparable results! This looks great.

Left a few minor comments. I think we should remove the custom scheduler function.

2022-06-02 01:32 UTC, abheesht17 commented on src/modules/schedulers.py
> +    return LambdaLR(optimizer, lr_lambda, last_epoch)
Let's remove this function.

2022-06-02 01:32 UTC, abheesht17 commented on src/modules/schedulers.py
> +ConfigMapper.map("schedulers", "linearwithwarmup")(get_linear_schedule_with_warmup)
I think we should remove this. We aren't using it. If we want to keep it, let's just use the function from `transformers` instead of defining our own function.

2022-06-02 14:22 UTC, dalgu90 commented on src/modules/schedulers.py
> +    return LambdaLR(optimizer, lr_lambda, last_epoch)
Right. Thanks for finding this out!

2022-06-02 14:25 UTC, dalgu90 commented on src/modules/schedulers.py
> +ConfigMapper.map("schedulers", "linearwithwarmup")(get_linear_schedule_with_warmup)
Thanks for pointing this out. I think we can keep this to refer to the `transformers` scheduler for future.

2022-06-18 07:28 UTC, abheesht17 approved these changes
LGTM! I've approved it, but I've left a few minor comments as well. Please address those and merge. Thanks!

2022-06-18 07:28 UTC, abheesht17 commented on src/models/multirescnn.py
> +            p.requires_grad = False
Do we use this function anywhere? Can't seem to find a reference to it.

2022-06-18 07:28 UTC, abheesht17 commented on src/models/multirescnn.py
> +            p.requires_grad = False
Same comment as the one for the other instance of this function.

2022-06-18 07:28 UTC, abheesht17 commented on src/models/multirescnn.py
> +            p.requires_grad = False
Same comment as the one for the other instance of this function.

2022-06-18 07:28 UTC, abheesht17 commented on src/models/multirescnn.py
> +"""
This does not have to be indented. Could you please unindent it?

2022-06-18 07:28 UTC, abheesht17 commented on src/models/multirescnn.py
> +                padding=int(floor(kernel_size / 2)),
Why do we need to typecast it to `int` here? `floor()` returns an integer, doesn't it?

2022-06-18 07:28 UTC, abheesht17 commented on src/utils/model_utils.py
> +    return vec / root_sum_square
This function can be deleted. We aren't using it anywhere.

2022-06-18 07:43 UTC, dalgu90 commented on src/models/multirescnn.py
> +                padding=int(floor(kernel_size / 2)),
This is from the original repo and maybe a practice of Python 2. `math.floor()` in Python 2 outputs float numbers. Will remove `int()` here.

2022-06-18 07:46 UTC, merged